// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kofqxhtknqysmpzzbmah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZnF4aHRrbnF5c21wenpibWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTIzNDYsImV4cCI6MjA1Nzc2ODM0Nn0.FGsZLLf_4b2IauzV-HsYTzaBVVM0Bztd9v1o-umgabI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);